### ISSUE TITLE
Download links on Wiki page no longer work

### ISSUE THREAD

**Issue by Kristine1975** [eriksvedang/SecretArcade#5]
The two download links on the Wiki page https://github.com/eriksvedang/SecretArcade/wiki both lead to a 404 page:

> Download the Secret Arcade for Mac: https://drive.google.com/open?id=0BxnlOFgp7hvFZDdpeERWT3lyR1E
> Download the Secret Arcade for Windows: https://drive.google.com/open?id=0BxnlOFgp7hvFQVhsRGtMeTdPckU

I'll admit that the game is 5 years old at this time, but maybe you still have the files and would be willing to upload them somewhere else?

P.S: Thank you for making `Else Heart.Break()`, and for making parts of the source code available (for better tinkering)!

**Comment by eriksvedang** [comment]
Thanks for informing me! I’ll try to set up the links again. Cheers!

**Comment by eriksvedang** [comment]
This should be fixed now.
